spring.application.name=Rate_Limiter_API
spring.cloud.gatewaty.discovery.locator.enabled=true


spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000

rate-limiter.capacity=5
rate-limiter.refill-rate=0
rate-limiter.api-server-url=http://localhost:8081
rate-limiter.timeout=5000

